server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # uri: file://Users/kimjungwon/Desktop/school/capstone/projectManagement/docs
          uri : https://github.com/jw0293/Spring-Cloud-Config

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh